name: CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bits: [32, 64]
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc-multilib g++-multilib
      - name: Run tests
        run: |
          ./tests/build_and_compile.sh ${{ matrix.bits }}
